"""add_growth_features

Revision ID: 1c73efb59542
Revises: 3e78b27eef6b
Create Date: 2026-02-07 04:52:29.895449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c73efb59542'
down_revision: Union[str, None] = '3e78b27eef6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create Enum types
    staffcontracttype = sa.Enum('salary', 'chair_rental', 'commission_only', 'hybrid', name='staffcontracttype')
    staffcontracttype.create(op.get_bind(), checkfirst=True)


    op.create_table('staff_goals',
    sa.Column('staff_id', sa.UUID(), nullable=False),
    sa.Column('establishment_id', sa.UUID(), nullable=False),
    sa.Column('goal_type', sa.Enum('revenue', 'services_count', 'customer_count', name='goaltype'), nullable=False),
    sa.Column('period', sa.Enum('daily', 'weekly', 'monthly', name='goalperiod'), nullable=False),
    sa.Column('target_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['establishment_id'], ['establishments.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_goals_establishment_id'), 'staff_goals', ['establishment_id'], unique=False)
    op.create_index(op.f('ix_staff_goals_staff_id'), 'staff_goals', ['staff_id'], unique=False)
    op.add_column('establishments', sa.Column('is_sponsored', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('establishments', sa.Column('sponsored_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('staff_members', sa.Column('contract_type', sa.Enum('salary', 'chair_rental', 'commission_only', 'hybrid', name='staffcontracttype'), server_default='commission_only', nullable=False))
    op.add_column('staff_members', sa.Column('base_salary', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff_members', 'base_salary')
    op.drop_column('staff_members', 'contract_type')
    op.drop_column('establishments', 'sponsored_until')
    op.drop_column('establishments', 'is_sponsored')
    op.drop_index(op.f('ix_staff_goals_staff_id'), table_name='staff_goals')
    op.drop_index(op.f('ix_staff_goals_establishment_id'), table_name='staff_goals')
    op.drop_table('staff_goals')
    # ### end Alembic commands ###
