"""model expansion staff bio and home services

Revision ID: 3e78b27eef6b
Revises: 67ee025fe6e9
Create Date: 2026-02-07 04:32:21.228333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e78b27eef6b'
down_revision: Union[str, None] = '67ee025fe6e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('is_at_home', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('staff_members', sa.Column('bio', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff_members', 'bio')
    op.drop_column('services', 'is_at_home')
    # ### end Alembic commands ###
