"""add product cost and markup

Revision ID: 67ee025fe6e9
Revises: 99c901766338
Create Date: 2026-02-07 04:27:57.815642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67ee025fe6e9'
down_revision: Union[str, None] = 'b2e4700baa1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('products', sa.Column('markup_percentage', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'markup_percentage')
    op.drop_column('products', 'cost_price')
    # ### end Alembic commands ###
