"""add_mercadopago_fields

Revision ID: 7cab3237c58b
Revises: eebf25e3c3a4
Create Date: 2026-02-08 17:43:52.110393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cab3237c58b'
down_revision: Union[str, None] = 'eebf25e3c3a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('establishments', sa.Column('mercadopago_user_id', sa.String(length=255), nullable=True))
    op.add_column('establishments', sa.Column('mercadopago_access_token', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('establishments', 'mercadopago_access_token')
    op.drop_column('establishments', 'mercadopago_user_id')
    # ### end Alembic commands ###
