"""add deposit_required to services

Revision ID: 99c901766338
Revises: c249f882956b
Create Date: 2026-02-05 20:44:44.666239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99c901766338'
down_revision: Union[str, None] = 'c249f882956b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('deposit_required', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'deposit_required')
    # ### end Alembic commands ###
