"""add cancellation and noshow fee columns to establishments

Revision ID: c249f882956b
Revises: 6ac068c6d2ac
Create Date: 2026-02-05 20:39:07.701313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c249f882956b'
down_revision: Union[str, None] = '6ac068c6d2ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('establishments', sa.Column('cancellation_fee_fixed', sa.Numeric(10, 2), nullable=False, server_default='0.0'))
    op.add_column('establishments', sa.Column('no_show_fee_percent', sa.Numeric(5, 2), nullable=False, server_default='0.0'))
    op.add_column('establishments', sa.Column('deposit_percent', sa.Numeric(5, 2), nullable=False, server_default='0.0'))
    op.add_column('establishments', sa.Column('pending_platform_fees', sa.Numeric(10, 2), nullable=False, server_default='0.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('establishments', 'pending_platform_fees')
    op.drop_column('establishments', 'deposit_percent')
    op.drop_column('establishments', 'no_show_fee_percent')
    op.drop_column('establishments', 'cancellation_fee_fixed')
    # ### end Alembic commands ###
