"""add_support_tickets

Revision ID: eebf25e3c3a4
Revises: 2f5ebca0bd87
Create Date: 2026-02-07 18:06:43.830601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eebf25e3c3a4'
down_revision: Union[str, None] = '2f5ebca0bd87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
